### ISSUE TITLE
Use a proper copyright symbol

### ISSUE THREAD

**Issue by alexander-dubinski** [tremckinley/tea-cozy#1]
https://github.com/tremckinley/tea-cozy/blob/fdf221f6da7b68292f557940acc0f6fa0143b4c8/index.html#L87

It is usually best to use the proper symbols when applicable/possible. This gives your site a professional feel and improves overall appearance. You can use a copyright symbol in your HTML by using what is called and HTML escape character, these are little codes which can be used to represent characters other than what you will find on a keyboard, an example for copyright is below, just copy and paste it into your HTML code

```&copy;```

**Comment by tremckinley** [comment]
That's good advice, thanks!
