### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by alexander-dubinski** [tremckinley/tea-cozy#2]
### Criteria 1: HTML Structure  
* _Score Level:_ 4 (exceeds expectations)
* _Comment(s):_ HTML structure is perfect and even has comments for each section, good
 
### Criteria 2: Visual Layout
* _Score Level:_ 4
* _Comment(s):_ Visual layout is immaculate with no major issues, just the copyright symbol (see other issues)
 
### Criteria 3: Use of Flexbox
* _Score Level:_ 4
* _Comment(s):_ Flexbox works as expected, great!
 
### Criteria 4: Implementation of Design Specification and Content
* _Score Level:_ 4
* _Comment(s):_ Document is within spec, no issues
 
### Overall Score: 16/16
Overall excellent job! I found very little to criticize so keep it up and happy coding!

**Comment by tremckinley** [comment]
I appreciate the feedback, flexbox felt like an important hurdle in growth. I'm looking forward to improving even more!
